name: Test Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main/**
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build -t web .
