name: Test Continuous Integration
run-name: Testing Docker Build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build -t web .
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publishing
        run: |
          echo "Publishing"
