name: Test Continuous Integration
run-name: Testing Docker Build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        run: |
          echo "Linting project..." \
          sleep 5s
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "Testing project..." \
          sleep 15s
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build -t web .
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publishing
        run: |
          echo "Publishing"
  e2e-test:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: E2E Testing
        run: |
          echo "E2E Testing"|
          sleep 20s
  success:
    needs: [publish, e2e-test]
    runs-on: ubuntu-latest
    steps:
      - name: "Successfully deployed"
        run: |
          echo "Successfully deployed" \
          sleep 5s
